version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
  - package-ecosystem: github-actions
    directory: /.github/actions/release-package
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
