sonar.organization=meymchen
sonar.projectKey=meymchen_banshu
sonar.projectName=banshu
sonar.sourceEncoding=UTF-8

sonar.sources=crates
sonar.exclusions=**/tests/**,**/target/**
sonar.tests=crates
sonar.test.inclusions=**/tests/**/*.rs

sonar.rust.lcov.reportPaths=coverage/lcov.info
